### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Matir** [mandatoryprogrammer/CursedChrome#1]
What license is this code under?  Can you add a LICENSE/COPYING file to clarify that?

**Comment by mandatoryprogrammer** [comment]
Added `LICENSE` file with MIT license here: https://github.com/mandatoryprogrammer/CursedChrome/commit/be09c6b1ecdcb09babc2c99e4879f399ab3a574c

Hope that works for your usage, let me know if something else would work better :)

**Comment by mandatoryprogrammer** [comment]
Feel free to file another issue if the MIT license doesn't fit you use case!
