### ISSUE TITLE
cursedchrome with Ngrok setup help

### ISSUE THREAD

**Issue by jepunband** [mandatoryprogrammer/CursedChrome#14]
hi, may i know the configuration of the ngrok setup & command please?

**Comment by Techbrunch** [comment]
You only have to update the connection URI  in `background.js`:

```
websocket = new WebSocket("https://z139d42bd69f7.ngrok.io");
```

**Comment by mandatoryprogrammer** [comment]
Closing out since this seems roughly handled (it's also not quite a question related specifically to this project, but rather a third-party service being used with it).
