### ISSUE TITLE
Duplicate headers are not properly handled

### ISSUE THREAD

**Issue by ZetaTwo** [mandatoryprogrammer/CursedChrome#15]
If the HTTP response to the victim contains multiple headers with the same key, for example:
```
...
Set-Cookie: A=B; attr1; attr2
Set-Cookie: X=Y; attr3; attr4
...
```

They will not be properly returned as separate headers from the proxy but instead concatenated into one like this:
```
Set-Cookie: A=B; attr1; attr2, X=Y; attr3; attr4
```
This breaks setting multiple cookies and possibly other response headers (though Set-Cookie is the only header explicitly forbidden to merge) as well. This can be solved by replacing the headers object with a list of key-value pairs to allow for multiple headers of the same key.

PS. Sorry for dropping a batch of issues like this. We have an ambition of providing PRs as well but letting you know about these things straight away in the meantime.

**Comment by mandatoryprogrammer** [comment]
Merged @psie's pull request so this should now be fixed! Thanks again @psie
