### ISSUE TITLE
later?

### ISSUE THREAD

**Issue by Lorenz11x** [mandatoryprogrammer/CursedChrome#2]
Hi Bryant, once I have installed CursedChrome CA for Proxying HTTPS in Kali Linux, google-crome, what should I do ??
Thanks and sorry for my English

**Comment by mandatoryprogrammer** [comment]
Github issues aren't really for help with the tool, you can take a look at this video which does a step-by-step tutorial on install it and setting it up though:
https://www.youtube.com/watch?v=cdSXdwa5trc
