### ISSUE TITLE
i need help pls showing error

### ISSUE THREAD

**Issue by ilyasse005** [mandatoryprogrammer/CursedChrome#31]
I used Ubuntu and Kali Linux

![Screenshot_2020-12-11_20-40-21](https://user-images.githubusercontent.com/52047430/101942265-87ff3400-3be9-11eb-98a0-12ef90e7c121.png)
![Screenshot_2020-12-11_00-20-54](https://user-images.githubusercontent.com/52047430/101942303-99e0d700-3be9-11eb-8a29-0f6088b95e34.png)

**Comment by mandatoryprogrammer** [comment]
Looks like you had some corruption while installing npm dependencies, try clearing your Docker layers cache for this image and re-running it.

**Comment by ilyasse005** [comment]
thank you it is working fine now

**Comment by ilyasse005** [comment]
thank you it is working fine now  
![Uploading sdd.png…]()

**Comment by mandatoryprogrammer** [comment]
Glad to hear 👍
