### ISSUE TITLE
npm issue

### ISSUE THREAD

**Issue by MichalGizaSrv** [mandatoryprogrammer/CursedChrome#4]
I have problem in step 6. Output:
![npm](https://user-images.githubusercontent.com/58888243/80787540-1bb64f80-8b87-11ea-8ee1-4dabe33f25ff.png)

`Step 6/22 : RUN npm install
 ---> Running in 7f45c4fbab3a
npm WARN croxy@1.0.0 No description
npm WARN croxy@1.0.0 No repository field.

npm ERR! network timeout at: https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-01T06_30_49_675Z-debug.log
ERROR: Service 'cursedchrome' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1
`

**Comment by mandatoryprogrammer** [comment]
Looks like a connection issue? A timeout for `registry.npmjs.org` is pretty odd considering that should be a CDN for all the `npm` packages. On the other hand, it is `npm` so who knows.

Either way it's not really a problem that's fixable by me, since I don't operate `npm`'s infra.
